pub mod auth;
pub mod contacts;
pub mod accounts;
pub mod leads;
pub mod pipeline;
pub mod deals;
pub mod notes;
pub mod activities;
pub mod products;
pub mod quotes;
pub mod emails;
pub mod admin;
pub mod settings;
pub mod views;

pub use auth::router as auth_router;
pub use contacts::router as contacts_router;
pub use accounts::router as accounts_router;
pub use leads::router as leads_router;
pub use pipeline::router as pipeline_router;
pub use deals::router as deals_router;
pub use notes::router as notes_router;
pub use activities::router as activities_router;
pub use products::router as products_router;
pub use quotes::router as quotes_router;
pub use emails::router as emails_router;
pub use admin::router as admin_router;
pub use settings::router as settings_router;
pub use views::router as views_router;
